permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Commit PDF to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) update paper.pdf'
          add:     'paper/paper.pdf'
