name: Build Paper PDF

on:
  push:
    paths:
      - 'paper/**'
      - '.github/workflows/draft-pdf.yml'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          # if you're targeting JOSS use "joss"; for JOSE use "jose"
          journal: joss
          # relative path to your Markdown source
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
